# Generated by Django 5.2 on 2025-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='author',
            field=models.CharField(default='Anonymous', max_length=150),
            preserve_default=False,
        ),
    ]
